APP_NAME=antiTheftTrackerApp
DB_USERNAME=postgres
DB_PASSWORD=postgres
DB_SOURCE_URL=jdbc:postgresql://localhost/antithefttracker_db
ENTERPRISE_ID=LC00kgdkrv
POLICY_NAME=vault_policy
VAULT_PACKAGE=com.antiTheftTracker.antiTheftTrackerApp
EMAIL_ADDRESS=embracegod92@gmail.com
EMAIL_PASSWORD=ghzt hnar ammv gtzo
MAIL_PORT=587
SMS_GATEWAY=mock
ADMIN_SDK=/keys/firebase/firebase-adminsdk.json