spring.config.import=classpath:application_secrets.properties

spring.application.name=${APP_NAME}
spring.datasource.url=${DB_SOURCE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

service.account.keys.base-path=classpath:keys/
service.account.keys.default-key-id=dev

android.management.enterprise.id=${ENTERPRISE_ID}
android.management.vault.policy.name=${POLICY_NAME}
android.management.vault.package=${VAULT_PACKAGE}

firebase.credentials-path=${ADMIN_SDK}
#android.management.service.account.key.path=classpath:keys/service-account.json




spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}
spring.mail.username=${EMAIL_ADDRESS}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

sms.gateway=${SMS_GATEWAY}
app.sms.mock-enabled=true
